classes:
  - name: "Team Enfant"
    location: "Paris 10"
    day_of_week: "Jeudi"
    time: "16:00-18:30"
    num_classes: 31
    color: "FF0000"
    start_date: "2024-09-12"
  
  - name: "Team Faubourg"
    location: "Paris 10"
    day_of_week: "Mercredi"
    time: "20:00-22:30"
    num_classes: 31
    color: "E3696E"
    start_date: "2024-09-12"
 
  - name: "Team Delta"
    location: "Paris 10"
    day_of_week: "Dimanche"
    time: "20:00-22:30"
    num_classes: 31
    color: "B1FCB2"
    start_date: "2024-09-12"

  - name: "Team Valmy"
    location: "Paris 10"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "A0BB87"
    start_date: "2024-09-12"

  - name: "Team Volontaires"
    location: "Paris 15"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "D5CDB5"
    start_date: "2024-09-12"

  - name: "Team Cite"
    location: "Paris 4"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "3882F6"
    start_date: "2024-09-12"

  - name: "Team Chatelet"
    location: "Paris 4"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "F6B8A5"
    start_date: "2024-09-12"

  - name: "Team Paradis"
    location: "Paris 10"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "AA8204"
    start_date: "2024-09-12"

  - name: "Team Petits carreaux"
    location: "Paris 10"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "BF50B8"
    start_date: "2024-09-12"

  - name: "Team Hotel de Ville"
    location: "Paris 4"
    day_of_week: "Mercredi"
    time: "20:00-22:30"
    num_classes: 31
    color: "1543AA"
    start_date: "2024-09-12"

  - name: "Team Provence"
    location: "Paris 10"
    day_of_week: "Jeudi"
    time: "20:00-22:30"
    num_classes: 31
    color: "8F7C3B"
    start_date: "2024-09-12"

  - name: "Team Long Form"
    location: "Paris 10"
    day_of_week: "Mercredi"
    time: "20:00-22:30"
    num_classes: 31
    color: "833417"
    start_date: "2024-09-12"

  - name: "Team Cambronne"
    location: "Paris 15"
    day_of_week: "Mardi"
    time: "20:00-22:30"
    num_classes: 31
    color: "55C4EC"
    start_date: "2024-09-12"

  - name: "Team Pont Marie"
    location: "Paris 4"
    day_of_week: "Mardi"
    time: "20:00-22:30"
    num_classes: 31
    color: "B62865"
    start_date: "2024-09-12"

  - name: "Team La Vilette"
    location: "Paris 10"
    day_of_week: "Mardi"
    time: "20:00-22:30"
    num_classes: 31
    color: "9F088B"
    start_date: "2024-09-12"

  - name: "Team Saint Denis"
    location: "Paris 10"
    day_of_week: "Lundi"
    time: "20:00-22:30"
    num_classes: 31
    color: "00FF00"
    start_date: "2024-09-12"

  - name: "Team Lepeletier"
    location: "Paris 10"
    day_of_week: "Mercredi"
    time: "20:00-22:30"
    num_classes: 31
    color: "E6A8C9"
    start_date: "2024-09-12"

  - name: "Team Comediens 2"
    location: "Paris 10"
    day_of_week: "Mardi"
    time: "10:30-13:00"
    num_classes: 31
    color: "71E83C"
    start_date: "2024-09-12"

  - name: "Team Comediens 1"
    location: "Paris 10"
    day_of_week: "Lundi"
    time: "10:30-13:00"
    num_classes: 31
    color: "040AA2"
    start_date: "2024-09-12"

  - name: "Team Lafayette"
    location: "Paris 10"
    day_of_week: "Mardi"
    time: "20:00-22:30"
    num_classes: 31
    color: "EAAFA4"
    start_date: "2024-09-12"

  - name: "Team Gare de l'est"
    location: "Paris 10"
    day_of_week: "Lundi"
    time: "20:00-22:30"
    num_classes: 31
    color: "641425"
    start_date: "2024-09-12"

  - name: "Team Hauteville"
    location: "Paris 10"
    day_of_week: "Mercredi"
    time: "20:00-22:30"
    num_classes: 31
    color: "B1FCB2"
    start_date: "2024-09-12"
